version: "3.7"
services:
  db:
    image: mysql:5.7
    hostname: db
    environment:
      MYSQL_DATABASE: cars
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
  cars:
    image: cars-backend
    hostname: cars
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 90
    depends_on:
      - db
    ports:
      - "3000:3000"
